Update and Optimize Docker Files (#338)
- Upgraded base OS versions and dependencies to their latest stable releases.
- Updated OQS Provider to 0.8.0 and liboqs to 0.12.0.

- Improved build processes:
  - Applied `apk add --no-cache` and `apt-get install --no-install-recommends` for efficient installations.
  - Ensured cleanup after installations to reduce image size.
  - Replaced `apt` with `apt-get` for consistency.

- Enhanced maintainability:
  - Introduced `WORKDIR` for better path management.
  - Quoted variables to avoid word splitting and potential errors.
  - Updated `ENV` instructions to use `key=value` format, resolving deprecation warnings.

- Removed obsolete and redundant components:
  - The `version` attribute from Docker Compose files, resolving warnings.
  - Unnecessary `DEBIAN_FRONTEND=noninteractive` from Alpine images.
  - Redundant upgrade steps during package installations.

- OpenSSH:
  - Fixed `/etc/profile.d/README` errors caused by invalid commands and syntax issues.
  - Customized the OpenSSH setup with a clean and informative welcome message.

Exclusions: OpenSSL 3, nginx/fulltest, Locust, and Mossquito Dockerfiles.

Signed-off-by: Khalid <187553667+itsHayyaf@users.noreply.github.com>

diff --git a/nginx/Dockerfile b/nginx/Dockerfile
--- a/nginx/Dockerfile
+++ b/nginx/Dockerfile
@@ -1,83 +1,59 @@
-# Multi-stage build: First the full builder image:
-
-# First: global build arguments:
-
-# define the alpine image version to use
-ARG ALPINE_VERSION=3.20
-
-# define the openssl tag to be used
+# Define build arguments for version tags, installation paths, and configurations
+ARG ALPINE_VERSION=3.21
 ARG OPENSSL_TAG=openssl-3.4.0
-
-# define the liboqs tag to be used
 ARG LIBOQS_TAG=0.12.0
-
-# define the oqsprovider tag to be used
 ARG OQSPROVIDER_TAG=0.8.0
-
-# liboqs build type variant; maximum portability of image:
-ARG LIBOQS_BUILD_DEFINES="-DOQS_DIST_BUILD=ON"
-
-# base install path
+ARG NGINX_VERSION=1.27.3
 ARG BASEDIR="/opt"
-
-# installation paths
 ARG INSTALLDIR=${BASEDIR}/nginx
 
-# defines the QSC signature algorithm used for the certificates:
+# Specify supported signature and key encapsulation mechanisms (KEM) algorithms
 ARG SIG_ALG="mldsa65"
-
-# defines the list of default groups to be activated in nginx-openssl config:
 ARG DEFAULT_GROUPS=x25519:x448:prime256v1:secp384r1:secp521r1:mlkem512:mlkem768:mlkem1024:X25519MLKEM768:SecP256r1MLKEM768
 
-# define the nginx version to include
-ARG NGINX_VERSION=1.27.2
-
-# Define the degree of parallelism when building the image; leave the number away only if you know what you are doing
-ARG MAKE_DEFINES="-j 18"
-
-
+# Stage 1: Build - Compile and assemble all necessary components and dependencies
 FROM alpine:${ALPINE_VERSION} AS intermediate
-# Take in global args
 ARG OPENSSL_TAG
 ARG LIBOQS_TAG
 ARG OQSPROVIDER_TAG
+ARG NGINX_VERSION
 ARG BASEDIR
-ARG LIBOQS_BUILD_DEFINES
 ARG INSTALLDIR
 ARG SIG_ALG
-ARG NGINX_VERSION
-ARG MAKE_DEFINES
 ARG DEFAULT_GROUPS
 ARG OSSLDIR=${BASEDIR}/openssl/.openssl
 
+# Install required build tools and system dependencies
+RUN apk update && apk --no-cache add \
+    build-base linux-headers libtool \
+    automake autoconf make cmake ninja \
+    openssl openssl-dev git wget pcre-dev
 
-# Get all software packages required for builing all components:
-RUN apk add build-base linux-headers \
-            libtool automake autoconf cmake ninja \
-            make \
-            openssl openssl-dev \
-            git wget pcre-dev
-
-# get OQS sources
+# Download and prepare source files needed for the build process
 WORKDIR /opt
-RUN git clone --depth 1 --branch ${LIBOQS_TAG} https://github.com/open-quantum-safe/liboqs && \
-    git clone --depth 1 --branch ${OQSPROVIDER_TAG} https://github.com/open-quantum-safe/oqs-provider.git && \
-    git clone --depth 1 --branch ${OPENSSL_TAG} https://github.com/openssl/openssl.git && \
-    wget nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && tar -zxvf nginx-${NGINX_VERSION}.tar.gz;
+RUN git clone --depth 1 --branch ${LIBOQS_TAG} https://github.com/open-quantum-safe/liboqs \
+    && git clone --depth 1 --branch ${OQSPROVIDER_TAG} https://github.com/open-quantum-safe/oqs-provider.git \
+    && git clone --depth 1 --branch ${OPENSSL_TAG} https://github.com/openssl/openssl.git \
+    && wget -q nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
+    && tar -zxf nginx-${NGINX_VERSION}.tar.gz \
+    && rm nginx-${NGINX_VERSION}.tar.gz
 
-# build liboqs (static only)
-WORKDIR /opt/liboqs
-RUN mkdir build && cd build && cmake -G"Ninja" ${LIBOQS_BUILD_DEFINES} -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=${INSTALLDIR} .. && ninja && ninja install
+# Build and install liboqs
+WORKDIR /opt/liboqs/build
+RUN cmake -G"Ninja"  \
+    -DOQS_DIST_BUILD=ON  \
+    -DBUILD_SHARED_LIBS=OFF  \
+    -DCMAKE_INSTALL_PREFIX="${INSTALLDIR}" ..  \
+    && ninja -j"$(nproc)" && ninja install
 
-# build nginx (also building openssl)
+# Build and install Nginx with custom OpenSSL and SSL support
 WORKDIR /opt/nginx-${NGINX_VERSION}
 RUN ./configure --prefix=${INSTALLDIR} \
-                --with-debug \
-                --with-http_ssl_module --with-openssl=/opt/openssl \
-                --without-http_gzip_module && \
-    make ${MAKE_DEFINES} && make install;
+    --with-debug --with-http_ssl_module  \
+    --with-openssl=/opt/openssl --without-http_gzip_module && \
+    make -j"$(nproc)" && make install
 
-# create openssl.cnf activating oqsprovider & setting default groups
+# Configure OpenSSL to support the oqs-provider
 RUN mkdir -p ${OSSLDIR=}/ssl && \
     cp /opt/openssl/apps/openssl.cnf ${OSSLDIR}/ssl/ && \
     sed -i "s/default = default_sect/default = default_sect\noqsprovider = oqsprovider_sect/g" ${OSSLDIR}/ssl/openssl.cnf && \
@@ -85,75 +61,69 @@ RUN mkdir -p ${OSSLDIR=}/ssl && \
     sed -i "s/providers = provider_sect/providers = provider_sect\nssl_conf = ssl_sect\n\n\[ssl_sect\]\nsystem_default = system_default_sect\n\n\[system_default_sect\]\nGroups = \$ENV\:\:DEFAULT_GROUPS\n/g" ${OSSLDIR}/ssl/openssl.cnf && \
     sed -i "s/HOME\t\t\t= ./HOME\t\t= .\nDEFAULT_GROUPS\t= ${DEFAULT_GROUPS}/g" ${OSSLDIR}/ssl/openssl.cnf
 
-# build oqsprovider
+# Build and install OQS provider
 WORKDIR /opt/oqs-provider
-
-RUN ln -s /opt/nginx/include/oqs ${OSSLDIR}/include && \
+RUN ln -s "/opt/nginx/include/oqs" "${OSSLDIR}/include" && \
     rm -rf build && \
-    cmake -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR=${OSSLDIR} -DCMAKE_PREFIX_PATH=$INSTALLDIR -S . -B build && \
+    cmake -DCMAKE_BUILD_TYPE=Debug \
+          -DOPENSSL_ROOT_DIR="${OSSLDIR}" \
+          -DCMAKE_PREFIX_PATH="${INSTALLDIR}" \
+          -S . -B build && \
     cmake --build build && \
-    export MODULESDIR=$(find ${OSSLDIR} -name ossl-modules) && \
-    cp build/lib/oqsprovider.so $MODULESDIR && \
-    mkdir -p ${OSSLDIR}/lib64 && \
-    ln -s ${OSSLDIR}/lib/ossl-modules ${OSSLDIR}/lib64 && \
-    rm -rf ${INSTALLDIR}/lib64
+    MODULESDIR=$(find "${OSSLDIR}" -name ossl-modules) && \
+    export MODULESDIR && \
+    cp build/lib/oqsprovider.so "${MODULESDIR}" && \
+    mkdir -p "${OSSLDIR}/lib64" && \
+    ln -s "${OSSLDIR}/lib/ossl-modules" "${OSSLDIR}/lib64" && \
+    rm -rf "${INSTALLDIR:?}/lib64"
 
+# Minimize image size, generate CA/server certificates, then cleanup
 WORKDIR ${INSTALLDIR}
+ENV PATH="${INSTALLDIR}/sbin:${OSSLDIR}/bin:${PATH}"
 
-# Test/Utilize oqsprovider:
-    # generate CA key and cert
-    # generate server CSR
-    # generate server cert
+RUN set -ex && \
+    strip "${OSSLDIR}/lib/"*.a "${OSSLDIR}/lib64/ossl-modules/oqsprovider.so" "${INSTALLDIR}/sbin/"* "${INSTALLDIR}/sbin/"* && \
+    mkdir -p cacert pki && \
+    openssl req -x509 -new -newkey "${SIG_ALG}" -keyout CA.key -out cacert/CA.crt -nodes -subj "/CN=oqstest CA" -days 365 -config "${OSSLDIR}/ssl/openssl.cnf" && \
+    openssl req -new -newkey "${SIG_ALG}" -keyout pki/server.key -out server.csr -nodes -subj "/CN=oqs-nginx" -config "${OSSLDIR}/ssl/openssl.cnf" && \
+    openssl x509 -req -in server.csr -out pki/server.crt -CA cacert/CA.crt -CAkey CA.key -CAcreateserial -days 365 && \
+    rm -f "${OSSLDIR}/bin/"*
 
-ENV PATH ${INSTALLDIR}/sbin:${OSSLDIR}/bin:$PATH
-# begin optimizing sizes:
-RUN strip ${OSSLDIR}/lib/*.a ${OSSLDIR}/lib64/ossl-modules/oqsprovider.so ${INSTALLDIR}/sbin/* ${INSTALLDIR}/sbin/*
-RUN set -x && \
-    mkdir cacert && \
-    mkdir pki && \
-    openssl req -x509 -new -newkey ${SIG_ALG} -keyout CA.key -out cacert/CA.crt -nodes -subj "/CN=oqstest CA" -days 365 -config ${OSSLDIR}/ssl/openssl.cnf && \
-    openssl req -new -newkey ${SIG_ALG} -keyout pki/server.key -out server.csr -nodes -subj "/CN=oqs-nginx" -config ${OSSLDIR}/ssl/openssl.cnf && \
-    openssl x509 -req -in server.csr -out pki/server.crt -CA cacert/CA.crt -CAkey CA.key -CAcreateserial -days 365
-
-# further optimize sizes:
-RUN rm ${OSSLDIR}/bin/*
-
-# second stage: Only create minimal image without build tooling and intermediate build results generated above:
+# Stage 2: Runtime - Create a lightweight image with essential binaries and configurations
 FROM alpine:${ALPINE_VERSION}
-# Take in global args
-ARG LIBOQS_BUILD_DEFINES
 ARG INSTALLDIR
 ARG SIG_ALG
 ARG BASEDIR
 ARG OSSLDIR=${BASEDIR}/openssl/.openssl
 
-LABEL version="3"
+# Install required build tools and system dependencies
+RUN apk update && apk --no-cache add pcre-dev
 
-RUN apk add pcre-dev
-
-# Only retain the ${*_PATH} contents in the final image
+# Copy compiled artifacts and configuration from the intermediate stage
 COPY --from=intermediate ${INSTALLDIR} ${INSTALLDIR}
 COPY --from=intermediate ${OSSLDIR} ${OSSLDIR}
 COPY nginx-conf/ ${INSTALLDIR}/nginx-conf
 
-WORKDIR ${INSTALLDIR}
+# Link logs to Docker collector
+RUN set -ex && \
+    ln -sf /dev/stdout "${INSTALLDIR}/logs/access.log" && \
+    ln -sf /dev/stderr "${INSTALLDIR}/logs/error.log"
 
-# forward request and error logs to docker log collector
-RUN ln -sf /dev/stdout ${INSTALLDIR}/logs/access.log && \
-    ln -sf /dev/stderr ${INSTALLDIR}/logs/error.log;
-
-# This expose command needs to be in line with what's spec'd in nginx.conf:
+# This expose command needs to be in line with what's specified in nginx.conf:
 EXPOSE 4433
 
-# Ensure nginx just runs
-ENV PATH ${INSTALLDIR}/sbin:$PATH
+# From Nginx 1.25.2: "nginx does not try to load OpenSSL configuration if the
+# --with-openssl option was used to build OpenSSL and the OPENSSL_CONF
+# environment variable is not set." Hence we must explicitly set OPENSSL_CONF.
+ENV PATH="${INSTALLDIR}/sbin:${PATH}" \
+    OPENSSL_CONF="${OSSLDIR}/ssl/openssl.cnf"
 
-STOPSIGNAL SIGTERM
+# Create non-root user and update permissions
+RUN addgroup -g 1000 -S oqs \
+ && adduser --uid 1000 -S oqs -G oqs \
+ && chown -R oqs:oqs "${INSTALLDIR}"
 
-# Enable a normal user to create new server keys off set CA
-RUN addgroup -g 1000 -S oqs && adduser --uid 1000 -S oqs -G oqs && chown -R oqs.oqs ${INSTALLDIR}
+# Run as non-root user
 USER oqs
-# From nginx 1.25.2: "nginx does not try to load OpenSSL configuration if the --with-openssl option was used to built OpenSSL and the OPENSSL_CONF environment variable is not set".
-# We therefore have to set the OPENSSL_CONF environment variable.
-ENV OPENSSL_CONF ${OSSLDIR}/ssl/openssl.cnf
+STOPSIGNAL SIGTERM
 CMD ["nginx", "-c", "nginx-conf/nginx.conf", "-g", "daemon off;"]
